@startuml Context
title "C4. Контекст"

!include <C4/C4_Container>

Person(analyst, "Спортивный аналитик", "Сравнивает статистику команд и игроков, анализирует результаты для разработки стратегий и тактик")
Person(coach, "Тренер", "Просматривает статистику своих игроков и команды, анализирует эффективность игроков на различных позициях, создает отчет о команде или игроке")
Person(player, "Игрок", "Отслеживает свои достижения, сравнивает статистику с другими игроками и анализирует прогресс")
Person(baseUser, "Пользователь", "Изучает статистику любимых игроков и команды, создает инфографику с лучшими моментами")
Person(journalist, "Журналист", "Пишет обзоры матчей, использует статистику для прогнозов и анализа ключевых моментов")
Person(tournamentOrganizer, "Организатор турниров", "Следит за ходом турниров, создает онлайн-табло и предоставляет актуальную статистику для участн")

System(sportsStatsSystem, "Система спортивной статистики", "Платформа для сбора, хранения и анализа статистики матчей, команд и игроков")

System_Ext(notificationSystem, "Система уведомлений", "Информирование пользователей о начале матча, результатах матчей и событиях")
System_Ext(backupSystem, "Система резервного копирования", "Создание и восстановление резервных копий данных")

analyst ---> sportsStatsSystem : Анализирует статистику команд и игроков
coach ---> sportsStatsSystem : Просматривает статистику игроков и команд, составляет отчеты
player ---> sportsStatsSystem : Отслеживает собственные достижения и результаты матчей
baseUser ---> sportsStatsSystem : Изучает статистику любимых команд и игроков
journalist ---> sportsStatsSystem : Пишет обзоры и создает прогнозы, используя статистику и результаты матчей
tournamentOrganizer ---> sportsStatsSystem : Управляет турниром и предоставляет статистику участникам

sportsStatsSystem ---> notificationSystem : Отправка уведомлений пользователям
sportsStatsSystem ---> backupSystem : Создание резервных копий данных

@enduml